version: '3'
services:
  app:
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - '5000:3000'
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
